### ISSUE TITLE
Feedback / Discussion (v2)

### ISSUE THREAD

**Issue by flowdee** [ahmadawais/WP-OOP-Settings-API#11]
Hey @ahmadawais ,

I already had some chats with @robertdevore and informed him that I would be interested in switching over to your Settings Class for [AAWP](https://getaawp.com) (and other projects as well). Additionally I would love to assist you and contribute to the project as well.

Therefore I collected some feedback which I would like to discuss with you guys:

In general I really like it! It looks clean, fast and is a very neat idea in order to make building setting pages with WP's API more comfortable.

Anyway there a few things which I would change:

## 1.) Isolating class-wp-osa.php
We have our class-wp-osa.php file which can be included in our projects in order to make use of the boilerplate, which is great.

But right now, due to the fact that some of the most important details are hardcoded inside this file. For example: 

```
add_options_page(
	'WP OOP Settings API',
	'WP OOP Settings API',
	'manage_options',
	'wp_osa_settings',
	array( $this, 'plugin_page' )
);
```

as well as:

`echo '<h1>WP OOP Settings API <span style="font-size:50%;">v' . WPOSA_VERSION . '</span></h1>';`

Both is crucial and change with every project.

In my opinion it would be a much better approach, to setup those details when initiating the class itself. For example:

```
$wposa_obj = new WP_OSA();

$wposa_obj->init(
	'id' => 'wpdis-settings'
	'page_title' => 'WP Dispensary - Settings',
	'menu_title' => 'Settings',
	'capability' => 'manage_options',
	'menu_slug' => 'wp_disp_settings'
);
```

Otherwise, whenever you enhance the original "class-wp-osa.php" in the repo (e.g. when adding new features, fixing bugs etc.), we can't simply replace the class file. We would also have to dig into the file and edit/add again our project related settings. 

I really think this project-related stuff should be initialized outsite of the class. The class itself should only hold the crucial functions/features and should be replacable in case there is a new version.

## 2.) Customizing settings page
In order to make the settings page brandable, we should add some hooks to the "plugin_page" function. For example

```
echo '<div class="wrap">';
do_action( 'wp_osa_settings_before', $this->ID );
echo '<h1>WP OOP Settings API <span style="font-size:50%;">v' . WPOSA_VERSION . '</span></h1>';
$this->show_navigation();
$this->show_forms();
do_action( 'wp_osa_settings_after', $this->ID );
echo '</div>';
```

This way we can hook into and e.g. add some banner/custom html at the top/bottom of the page in order to brand the settings page.

## 3.) Support for add_submenu_page
Right now you're only providing a way to add a settings page to the "Settings" menu item. When thinking about our plugins, we would like to move this settings page right under our very own menu item instead.

So there should be a way to decide whether to use "add_options_page" or "add_submenu_page". In case of a submenu page, we would have to pass the parent menu slug of course.

--

As said in the beginning, I really like the approach and how it's already built. In case you agree that my enhancements would make sense, I would help to improve the class (if you like) and also use it in my projects.

Would love to know what you think about the points mentioned above 👍

**Comment by flowdee** [comment]
I can see that you're right now displaying every section in a different form. This leads into the following issue: When you make some edits on tab 1, switch to tab 2 and save there. All other editingsb (from tab 1 etc) will be lost.

If you want to make tabs changeable without page load, all options must be placed under the same form.

Otherwise you can of course use 1 form per section, but then clicking on a tab must lead into loading the page as standard link.

What's your opinion on this?

**Comment by ahmadawais** [comment]
@flowdee Thanks for offering to help. Lots of things that I open source are tied way to tightly with my personal workflows which are not always perfect (depends on the amount of time I have and when I coded that).

This project has a lot of potential if we can make it more flexible, and define a better standard. It can become a go-to resource for the WordPress community. 

I agree with all the three changes you proposed. 

I'd like to invite you as a collaborator here on the project, together with @robertdevore you folks can create an awesome new version 2.0.0 of this library and we can all do a relaunch if the repo. It'd be an effort appreciated by the community.


Take a look at roadmaps of two of my projects:
- Proposed: https://github.com/ahmadawais/create-guten-block/issues/11
- Proposes + Work In Progress: https://github.com/ahmadawais/WPGulp/issues/61

I've started one for this project

- https://github.com/ahmadawais/WP-OOP-Settings-API/issues/12

Let's create separate issues for each and assign it to whoever is working on them. Also, discuss everything in the issue I just mentioned instead of here.
